# Generated by Django 3.2.24 on 2024-02-11 07:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240209_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
